# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [20]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bappa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bappa/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bappa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bappa/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bappa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bappa/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bappa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bappa/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10

In [21]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [22]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [23]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [24]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [25]:
arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


#### 8.  Reverse a vector (first element becomes last)

In [26]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
arr = np.random.randint(0,9,(3,3))
arr

array([[7, 2, 7],
       [6, 6, 4],
       [1, 5, 1]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [28]:
arr = np.array([1,2,0,0,4,0])
ans =  np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [30]:
np.random.random((3 , 3 , 3))

array([[[0.1650693 , 0.50116748, 0.79168894],
        [0.11984107, 0.28319561, 0.98176505],
        [0.94995094, 0.95727507, 0.84383163]],

       [[0.08177836, 0.5780074 , 0.96595727],
        [0.31321823, 0.90415627, 0.12016116],
        [0.38851952, 0.60640081, 0.09580369]],

       [[0.90454802, 0.33660585, 0.3823585 ],
        [0.29269999, 0.52278174, 0.75827345],
        [0.93577285, 0.16130244, 0.56887799]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [31]:
arr = np.random.random((10 , 10))
a = np.max(arr)
b = np.min(arr)
print(a , b , sep = "\n")

0.9651381309160916
0.009072123570484925


#### 14. Create a random vector of size 30 and find the mean value

In [32]:
np.random.random((30))
ans = np.mean(arr)
ans

0.5087931999186843

#### 15. Create a 2d array with 1 on the border and 0 inside

In [33]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [34]:
arr = np.ones((5,5))
np.pad(arr,pad_width=1 , mode="constant" , constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [36]:
arr = np.diag([1 , 2 , 3 , 4],-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

 Solved Numpy Exercise